# RWR 车辆解析配置
package_path:
  - "C:\\Users\\hongx\\Documents\\test_sub"
output_format: "json"
pretty_print: true
include_source: false

defaults:
  inherit_enabled: true
  base_attr: "file"

entities:
  vehicle:
    selector: "vehicle"
    name: "vehicle"
    is_array: false

    attributes:
      - source: "@name"
        target: "name"
      - source: "@key"
        target: "key"
      - source: "@file"
        target: "inherit_from"
      - source: "@respawn_time"
        target: "respawn_time"
        transform: "to_float"
      - source: "@time_to_live_unsteerable"
        target: "unsteerable_ttl"
        transform: "to_float"
      - source: "@map_view_atlas_index"
        target: "map_index"
        transform: "to_int"
      - source: "@minimum_fill_requirement"
        target: "min_fuel"
        transform: "to_float"

    children:
      tags:
        selector: "tag"
        name: "tags"
        is_array: true
        attributes:
          - source: "@name"
            target: "name"

      tire_sets:
        selector: "tire_set"
        name: "tire_sets"
        is_array: true
        attributes:
          - source: "@offset"
            target: "offset"
            transform: "parse_vector3"
          - source: "@radius"
            target: "radius"
            transform: "to_float"

      control:
        selector: "control"
        name: "control"
        is_array: false
        attributes:
          - source: "@max_speed"
            target: "max_speed"
            transform: "to_float"
          - source: "@acceleration"
            target: "acceleration"
            transform: "to_float"
          - source: "@max_reverse_speed"
            target: "max_reverse_speed"
            transform: "to_float"
          - source: "@min_health_to_steer"
            target: "min_health_to_steer"
            transform: "to_float"
          - source: "@max_rotation"
            target: "max_rotation"
            transform: "to_float"
          - source: "@max_water_depth"
            target: "max_water_depth"
            transform: "to_float"
          - source: "@steer_smoothening"
            target: "steer_smoothening"
            transform: "to_float"

      physics:
        selector: "physics"
        name: "physics"
        is_array: false
        attributes:
          - source: "@max_health"
            target: "max_health"
            transform: "to_float"
          - source: "@blast_damage_threshold"
            target: "blast_damage_threshold"
            transform: "to_float"
          - source: "@mass"
            target: "mass"
            transform: "to_float"
          - source: "@broken_mass"
            target: "broken_mass"
            transform: "to_float"
          - source: "@remove_collision_threshold"
            target: "remove_collision_threshold"
            transform: "to_float"
          - source: "@extent"
            target: "extent"
            transform: "parse_vector3"
          - source: "@offset"
            target: "offset"
            transform: "parse_vector3"
          - source: "@top_offset"
            target: "top_offset"
            transform: "parse_vector3"
          - source: "@collision_model_pos"
            target: "collision_model_pos"
            transform: "parse_vector3"
          - source: "@collision_model_extent"
            target: "collision_model_extent"
            transform: "parse_vector3"
          - source: "@visual_offset"
            target: "visual_offset"
            transform: "parse_vector3"
          - source: "@friction_offset"
            target: "friction_offset"
            transform: "to_float"
          - source: "@drag_offset"
            target: "drag_offset"
            transform: "to_float"

      turret:
        selector: "turret"
        name: "turret"
        is_array: false
        attributes:
          - source: "@offset"
            target: "offset"
            transform: "parse_vector3"
          - source: "@weapon_key"
            target: "weapon_key"
          - source: "@weapon_offset"
            target: "weapon_offset"
            transform: "parse_vector3"
          - source: "@weapon_recoil"
            target: "weapon_recoil"
            transform: "to_float"
          - source: "@max_rotation_step"
            target: "max_rotation_step"
            transform: "to_float"

      visuals:
        selector: "visual"
        name: "visuals"
        is_array: true
        attributes:
          - source: "@class"
            target: "class"
          - source: "@key"
            target: "key"
          - source: "@mesh_filename"
            target: "mesh"
          - source: "@texture_filename"
            target: "texture"

      character_slots:
        selector: "character_slot"
        name: "character_slots"
        is_array: true
        attributes:
          - source: "@type"
            target: "type"
          - source: "@position"
            target: "position"
            transform: "parse_vector3"
          - source: "@rotation"
            target: "rotation"
            transform: "to_float"
          - source: "@exit_rotation"
            target: "exit_rotation"
            transform: "to_float"
          - source: "@hiding"
            target: "hiding"
            transform: "to_float"
        children:
          weapon_slots:
            selector: "weapon_slot"
            name: "weapon_slots"
            is_array: true
            attributes:
              - source: "@allowed"
                target: "allowed_weapon"

      rev_sounds:
        selector: "rev_sound"
        name: "rev_sounds"
        is_array: true
        attributes:
          - source: "@filename"
            target: "filename"
          - source: "@low_pitch"
            target: "low_pitch"
            transform: "to_float"
          - source: "@high_pitch"
            target: "high_pitch"
            transform: "to_float"
          - source: "@low_rev"
            target: "low_rev"
            transform: "to_float"
          - source: "@high_rev"
            target: "high_rev"
            transform: "to_float"
          - source: "@volume"
            target: "volume"
            transform: "to_float"

      sounds:
        selector: "sound"
        name: "sounds"
        is_array: true
        attributes:
          - source: "@key"
            target: "key"
          - source: "@filename"
            target: "filename"

      effects:
        selector: "effect"
        name: "effects"
        is_array: true
        attributes:
          - source: "@event_key"
            target: "event"
          - source: "@type"
            target: "type"
          - source: "@key"
            target: "key"
          - source: "@surface_tag"
            target: "surface_tag"
          - source: "@size"
            target: "size"
            transform: "to_float"
          - source: "@atlas_index"
            target: "atlas_index"
            transform: "to_int"
          - source: "@layer"
            target: "layer"
            transform: "to_int"
          - source: "@ref"
            target: "ref"
          - source: "@use_surface_color"
            target: "use_surface_color"
            transform: "to_bool"
          - source: "@value"
            target: "value"
            transform: "to_float"
          - source: "@offset"
            target: "offset"
            transform: "parse_vector3"
          - source: "@post_processing"
            target: "post_processing"
            transform: "to_bool"
          - source: "@shadow"
            target: "shadow"
            transform: "to_bool"

      events:
        selector: "event"
        name: "events"
        is_array: true
        attributes:
          - source: "@key"
            target: "key"
        children:
          trigger:
            selector: "trigger"
            name: "trigger"
            is_array: false
            attributes:
              - source: "@class"
                target: "class"
          result:
            selector: "result"
            name: "result"
            is_array: false
            attributes:
              - source: "@class"
                target: "class"
              - source: "@xp"
                target: "xp"
                transform: "to_float"
              - source: "@rp"
                target: "rp"
                transform: "to_float"
              - source: "@instance_class"
                target: "instance_class"
              - source: "@instance_key"
                target: "instance_key"
              - source: "@min_amount"
                target: "min_amount"
                transform: "to_int"
              - source: "@max_amount"
                target: "max_amount"
                transform: "to_int"
              - source: "@offset"
                target: "offset"
                transform: "parse_vector3"
              - source: "@position_spread"
                target: "position_spread"
                transform: "parse_vector2"
              - source: "@direction_spread"
                target: "direction_spread"
                transform: "parse_vector2"
